import { chromium } from 'playwright';
const [img, out, x, y, w, h] = process.argv.slice(2);
const src = 'file:///' + img.replace(/\\/g, '/');
const b = await chromium.launch({ channel: 'chrome' });
const p = await b.newPage({ viewport: { width: 1400, height: 3000 }, deviceScaleFactor: 2 });
await p.goto(src, { waitUntil: 'load' });
await p.evaluate(() => {
  const im = document.querySelector('img');
  im.style.width = '1320px';
  im.style.height = 'auto';
  im.style.maxWidth = 'none';
  im.style.position = 'absolute';
  im.style.left = '0';
  im.style.top = '0';
  document.body.style.margin = '0';
});
await p.waitForTimeout(400);
await p.screenshot({ path: out, clip: { x: Number(x), y: Number(y), width: Number(w), height: Number(h) } });
await b.close();
console.log('拡大:', out);
